#msg5846 touchpanel driver


obj-$(CONFIG_TOUCHSCREEN_MSG5846)   += mstar_drv_common.o \
mstar_drv_fw_control.o \
mstar_drv_hotknot.o \
mstar_drv_hotknot_queue.o \
mstar_drv_ic_fw_porting_layer.o \
mstar_drv_jni_interface.o \
mstar_drv_main.o \
mstar_drv_mp_test.o \
mstar_drv_platform_interface.o \
mstar_drv_platform_porting_layer.o \
mstar_drv_qcom.o \
mstar_drv_utility_adaption.o
