#
# Makefile for MELFAS MIP4 Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438) 	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms438.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449) 	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms438.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS458) 	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms438.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS500) 	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mms500.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MCS8040L)	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mcs8040l.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT200) 	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mit200.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIT300) 	+= mip4.o mip4_mod.o mip4_debug.o mip4_fw_mit300.o

